// <auto-generated />
namespace MilitaryShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImageBasket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageBasket));
        
        string IMigrationMetadata.Id
        {
            get { return "202101151139318_Image-Basket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
